version: '3.7'

networks:
  backend:
    driver: bridge

services:
  nginx:
    build:
      context: docker/nginx
    container_name: nginx_Bnovo
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - backend

  db:
    build:
      context: docker/mysql
    container_name: db_Bnovo
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - ./data/mysql/dump:/docker-entrypoint-initdb.d
    networks:
      - backend

  php:
    build:
      context: docker/php-fpm
    container_name: php_Bnovo
    volumes:
      - ./src:/var/www
#      - ./php-fpm/my-php.ini:/usr/local/etc/php/conf.d/my-php.ini
    ports:
      - "9000:9000"
    networks:
      - backend